### ISSUE TITLE
labels of loaded files modified and loose of opened files after restart

### ISSUE THREAD

**Issue by joede** [codebrainz/overview-plugin#19] opened 2015-10-21 05:29 UTC
I've installed todays HEAD of the master branch running the official Geany 1.24.1 on Debian 8. The build works fine and the installation is done into `~/local/...` without problems. I've added the full path to this plugin location in the configuration dialog of Geany. The plugin can be loaded and it displays the overview as expected.

After loading the plugin, the labels of the notebook tabs changes from the filenames to "Page 1", "Page 2", and so on (here I see the German translation). The content is still the same as before.
After a restart of Geany, only a single empty tab labeles with "Page 1" is shown.

Calling Geany with `-v` doesn't show something special. After that, I've disabled the plugin and after a restart the filenames are shown again as label, and Geany remembers the opened files again.

**Comment by b4n** [comment] 2015-10-21 13:01
Duplicate of #9.

**Closed as completed by b4n** 2015-10-21 13:01 UTC
